### ISSUE TITLE
Support for GNOME Shell 44

### ISSUE THREAD

**Issue by fabaff** [Josholith/gnome-extension-lan-ip-address#19]
It would be much appreciated if support for Gnome 44 is added.

Thanks

**Comment by Josholith** [comment]
GNOME Shell 44 support has been added.

Updated extension has been published and is available on the official extensions site https://extensions.gnome.org/extension/1762/lan-ip-address/

**Comment by fabaff** [comment]
Thank you very much, @Josholith
