### ISSUE TITLE
5 seconds refresh time is too low

### ISSUE THREAD

**Issue by pedro-muniz** [Josholith/gnome-extension-lan-ip-address#3]
For a workstation execute "ip route" with 5 seconds delay is not necessary. You could set refresh time for 5 minutes or click.

**Comment by Josholith** [comment]
A longer polling interval is probably fine for a desktop workstation use case.  For laptops or mobile devices where my address is more likely to change I wanted the refresh to be pretty quick, like when resuming from suspend going between two locations (like home and work).

Was there some side effect that prompted you to look into the refresh interval (like high CPU utilization or too much logging)?
